### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MrTip0** [MrTip0/weather#1]
# TODO

- [ ] Add geolocation
- [ ] Add language selection
- [ ] Add better descriptions
- [ ] Add future days forecasts
- [ ] Make a better GUI
